### ISSUE TITLE
Need to provide value in food allergy field to create account

### ISSUE THREAD

**Issue by oggnik** [oggnik/acm-hscc#9]
If you leave the food allergy field free the registration process drops a massive error.

**Comment by oggnik** [comment]
This was the error:

```
    Traceback (most recent call last):
      File "/Library/Python/2.7/site-packages/flask/app.py", line 1836, in __call__
        return self.wsgi_app(environ, start_response)
      File "/Library/Python/2.7/site-packages/flask/app.py", line 1820, in wsgi_app
        response = self.make_response(self.handle_exception(e))
      File "/Library/Python/2.7/site-packages/flask/app.py", line 1403, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
      File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
      File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/Users/nickiogg/Documents/School/Fall_2015/ACM/acm-hscc/hscc/controllers.py", line 38, in register
        db.session.add(form.allergies)
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
        return getattr(self.registry(), name)(*args, **kwargs)
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 1586, in add
        raise exc.UnmappedInstanceError(instance)
    UnmappedInstanceError: Class '__builtin__.NoneType' is not mapped
```
